### ISSUE TITLE
Queue throttle explanation

### ISSUE THREAD

**Issue by Albus** [fireworq/fireworq#153]
Can you please explain how exactly the parameters are used:
- Max Dispatches Per Second
- Max Burst Size

There is a new functionality, but nothing is said in the documentation. Thks :)

**Comment by tarao** [comment]
It is described in the parameter list of [<code>PUT /queue/<var>{queue_name}</var></code> API](https://github.com/fireworq/fireworq/blob/af095eed10b6874c438449bed186f71e0396db32/doc/api.md#api-put-queue).  Please let us know if the explanation is unclear to you.

**Comment by Albus** [comment]
> `max_dispatches_per_second` - _The maximum floating-point number of dispatches allowed to be processed within a second for this queue._ 

dispatches, whether it is possible to define the term more precisely. The number of what exactly.

> `max_burst_size` - _The maximum number of burst size of throttling configuration for this queue._

number of burst size of throttling configuration - I can't understand this term

**Comment by tarao** [comment]
"**Dispatches**" (or "job dispatches") means the number of jobs delivered to (external) workers.  When we say "to dispatch a job", it means "to make an external call to a worker giving a job payload".

"**Burst size**" is the number of jobs that can be dispatched at once.  This means that until this number, the number of dispatches may exceed `max_dispatches_per_second` in a short period of time.  If you wish to limit the number strictly, you should set `1` for `max_burst_size`.  I think the notion of "burst size" is quite common.  We taken the term from [`Burst` in `rate` package of golang.org/x/time](https://pkg.go.dev/golang.org/x/time/rate#Limiter.Burst) but similar things are seen in many other places for example [`burst` in `limit_req` directive of Nginx](http://nginx.org/en/docs/http/ngx_http_limit_req_module.html#limit_req).

**Comment by Albus** [comment]
Thanks a lot
