### ISSUE TITLE
About use in production with kubernetes

### ISSUE THREAD

**Issue by murata100** [fireworq/fireworq#168]
Is it possible to create a deployment on kubernetes using the official docker image and put it into production?

docker image: `fireworq/fireworq`

**Comment by tarao** [comment]
It should be possible but I can hardly tell you further since I'm not a k8s expert.

**Comment by murata100** [comment]
@tarao 
"Deployment on kubernetes" here simply means that 1 ~ n Docker containers that refer to the same database will be started at the same time.

If I launch more than one Docker container (replicas> = 2)
Isn't it a FIFO order even if max_workers = 1?
Thanks

**Comment by tarao** [comment]
If you have multiple Fireworq containers that refer to the same database, only one of them becomes the primary node and others will be backup nodes (for each queue).  You can `POST` / enqueue  a job to either node but the job is always grabbed / processed by the primary node.  This guarantees FIFO order if you have `max_workers` = 1.  (`max_workers` is nothing to do with the number of Firewroq containers.  It decides the number of concurrent threads inside a single Fireworq node.)

**Comment by murata100** [comment]
Excellent !

It's good to document it, if not yet (together with #167).
