### ISSUE TITLE
PUT /queue/{queue_name} waited for job completion, if the queue already exists and any job is executing

### ISSUE THREAD

**Issue by murata100** [fireworq/fireworq#182]
[PUT /queue/{queue_name}](https://github.com/fireworq/fireworq/blob/master/doc/api.md#api-put-queue) waited for job completion, if the queue already exists and any job is executing.

How to solve

Check if queue exists in advance with [GET /queue/{queue_name}](https://github.com/fireworq/fireworq/blob/master/doc/api.md#api-get-queue)

- check Status 404 or 200
- and is your (will POST) request Body a subset of the body in the response (of GET)

The advantage of idempotent operations is lost because pre-checks need to be performed.

**Comment by tarao** [comment]
I prepared a fix not to reload queues after `PUT`ing a queue if there is no change.

----

> request Body a subset of the body in the response

Be aware that this condidition is incorrect: if your request body lacks `polling_interval` for example, then reloading should be skipped only if `polling_interval` in the response is the same as [the default value](https://github.com/fireworq/fireworq/blob/master/doc/config.md#env-queue-default-polling-interval).
