### ISSUE TITLE
Getting connection refused on localhost/127.0.0.1

### ISSUE THREAD

**Issue by zeeshanjan82** [fireworq/fireworq#198]
I am getting the following error:
`{"level":"info","time":1684308498587,"tag":"fireworq.queue","action":"complete","queue":"default","category":"foo","id":11,"status":"failed","created_at":1684308498471,"elapsed":116,"url":"http://172.17.0.2:3000/work","payload":"{\"id\":12345}","next_try":1684308498471,"retry_count":0,"retry_delay":0,"fail_count":1,"timeout":0,"message":"Request failed: Post \"http://172.17.0.2:3000/work\": dial tcp 172.17.0.2:3000: connect: connection refused"}`

when I am running the command:
`curl -XPOST -d '{"url":"http://172.17.0.2:3000/work","payload":{"id":12345}}' http://localhost:8080/job/foo`

I have a simple node.js service running in localhost on port 3000
using this code:
```
const http = require('http');

const hostname = 'localhost';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'application/json');
  res.end(JSON.stringify({ status:"success", message:"It's working!" }));
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```

my docker container bridge is
![image](https://github.com/fireworq/fireworq/assets/8342604/de2261c7-918b-4d68-bcb8-f95368058fd5)

**Comment by tarao** [comment]
Try this:

replace

```
const hostname = 'localhost';
```

with

```
const hostname = '0.0.0.0';
```

in your code.

Listening on `localhost:3000` doesn't accept connection from docker network AFAIK.

**Comment by zeeshanjan82** [comment]
thanks @tarao I am running docker using the command:
`docker run -p 8080:8080 fireworq/fireworq --driver=in-memory --queue-default=default`
and now I have change the node service so it is running on 0.0.0.0:3000
`Server running at http://0.0.0.0:3000/`
but when I run the command:
`curl -XPOST -d '{"url":"http://0.0.0.0:3000","payload":{"id":12345}}' http://localhost:8080/job/foo `
or 
`curl -XPOST -d '{"url":"http://172.17.0.2:3000/work","payload":{"id":12345}}' http://0.0.0.0:8080/job/foo`
or
`curl -XPOST -d '{"url":"http://127.0.0.1:3000","payload":{"id":12345}}' http://localhost:8080/job/foo  ` 
I am getting error:

`{"level":"info","time":1684309433702,"tag":"fireworq.queue","action":"complete","queue":"default","category":"foo","id":7,"status":"failed","created_at":1684309433610,"elapsed":92,"url":"http://172.17.0.2:3000/work","payload":"{\"id\":12345}","next_try":1684309433610,"retry_count":0,"retry_delay":0,"fail_count":1,"timeout":0,"message":"Request failed: Post \"http://172.17.0.2:3000/work\": dial tcp 172.17.0.2:3000: connect: connection refused"}`

**Comment by tarao** [comment]
How about `curl -XPOST -d '{"url":"http://172.17.0.1:3000","payload":{"id":12345}}' http://localhost:8080/job/foo `  or `curl -XPOST -d '{"url":"http://host.docker.internal:3000","payload":{"id":12345}}' http://localhost:8080/job/foo `  ?

I'm assuming you are running the command on your docker host and your node.js service is running on the same host.

**Comment by zeeshanjan82** [comment]
@tarao still getting connection refused both node service and docker are on the same machine
![image](https://github.com/fireworq/fireworq/assets/8342604/d54e60ef-d88d-4a5b-8363-5b2bcadf00ba)

**Comment by tarao** [comment]
You are running two commands with `or`.  Just try this:

```
curl -XPOST -d '{"url":"http://172.17.0.1:3000","payload":{"id":12345}}' http://localhost:8080/job/foo
```

**Comment by zeeshanjan82** [comment]
@tarao I am still getting the same error when using the curl command, I have shared the screenshot of 3 things, node service, docker and the curl command
![image](https://github.com/fireworq/fireworq/assets/8342604/0b3957d6-2817-445d-a246-cf4b0a9abfbe)

**Comment by tarao** [comment]
How about this?

```
curl -XPOST -d '{"url":"http://host.docker.internal:3000","payload":{"id":12345}}' http://localhost:8080/job/foo
```

**Comment by zeeshanjan82** [comment]
@tarao yes now it is working, thanks for having all the patience with me :)
![image](https://github.com/fireworq/fireworq/assets/8342604/4f8d6e2a-64aa-4f39-8c48-a678a2b41d0d)

**Comment by zeeshanjan82** [comment]
@tarao I have a question, I am trying to send the request using PHP code like this 

![image](https://github.com/fireworq/fireworq/assets/8342604/89630490-949d-4aa6-8585-1ee9a21507ec)

but I am getting response:

{"level":"info","remote_addr":"172.17.0.1","tag":"fireworq.access","method":"POST","url":"/job/foo","status":400,"duration":0.047973,"time":"2023-05-22T10:05:05Z"}

in docker terminal.
