### ISSUE TITLE
What are the system requirements?

### ISSUE THREAD

**Issue by Hsn723** [fireworq/fireworq#23]
Do you have an estimate on the minimal/recommended system requirements for running a fireworq instance? I'm mostly looking for CPU/memory requirements, but if you can provide anything else it would be very appreciated.

**Comment by tarao** [comment]
It depends on how hard you use it but in general you don't need any special hardware for it.

If you use a single queue and there is a very small amount of jobs at a time, for example only one job per second, then few resources and no multi-core processor are required.

If you have a relatively large amount of jobs at a time, for example 100 jobs per second, then you need stronger CPU but they can still be handled by a normal PC like my laptop, which has 8-core Intel Core i7 and memory consumption won't be so high.  It would rather be a matter of worker hosts being capable of handling such amount of jobs.

I'll give you some information from real usage.  On my laptop, after running [a benchmark](https://github.com/fireworq/benchworker), the memory consumption (RSS) was 17,196 kB.  On our production Fireworq servers, that handle about some hundred jobs per second by less than 10 queues, it was about 14~16 MB.  They have something like 4-core Xeon but the CPU usage is only a few percent.  (It is far from using the full resources.)

Note that if you think about giving a really large amount of jobs at a time, you may need to `sysctl` (to set `/etc/sysctl.conf`) to avoid socket starvation something like this:

```
net.core.somaxconn = 4096
net.core.netdev_max_backlog = 4096
net.ipv4.tcp_max_syn_backlog = 4096
net.ipv4.tcp_tw_reuse = 1
```

**Comment by Hsn723** [comment]
Thank you very much for the detailed analysis and real usage information! It is very helpful.
