### ISSUE TITLE
Creating official Docker Hub image

### ISSUE THREAD

**Issue by ultd** [fireworq/fireworq#36]
Great project, I am very interested in using this in my own project but would like to deploy in Kubernetes and am finding a bit difficult to build these images locally (not using docker-compose). Any chance you can create a docker image and push an official image to docker hub?

**Comment by tarao** [comment]
Yes, we would like to have an official image but it will take some time.

For now, you have to write your own `Dockerfile`, which should look like this:

```dockerfile
FROM alpine:3.10

ENV FIREWORQ_QUEUE_DEFAULT default
ENV FIREWORQ_BIND 0.0.0.0:8080

RUN apk --no-cache add curl unzip jq \
 && mkdir -p /tmp/build \
 && curl -L $(curl -sL  https://api.github.com/repos/fireworq/fireworq/releases/latest | jq -r '.assets[].browser_download_url' | grep "_linux_amd64.zip") -o /tmp/build/fireworq_linux_amd64.zip \
 && cd /usr/local/bin \
 && unzip /tmp/build/fireworq_linux_amd64.zip fireworq \
 && chmod a+x /usr/local/bin/fireworq \
 && rm -rf /tmp/build \
 && apk del --purge curl unzip \
 && fireworq --version

EXPOSE 8080

CMD ["fireworq"]
```

It should run like this:

```
docker build firworq-image -f Dockerfile
```
```
docker run -p 8080:8080 fireworq-image fireworq --mysql-dsn="nobody:nobody@tcp(172.17.0.1:3306)/fireworq?parseTime=true&charset=binary"
```

where `172.17.0.1:3306` points to your MySQL server (it is on the host machine in this case) and you need a database named `fireworq` which can be accessed by `nobody` with password `nobody`.

Note that you may have to include [start_server](https://metacpan.org/pod/distribution/Server-Starter/script/start_server) (or something compatible with that) in the image to let Fireworq gracefully restart/shut down.  (Read [the doc](https://github.com/fireworq/fireworq/blob/master/doc/production.md) for the detail.)

**Comment by zain1992** [comment]
Ok, great thanks for your help. Looking forward to the official Docker hub image.

**Comment by itchyny** [comment]
We released to Docker Hub [fireworq/fireworq](https://hub.docker.com/r/fireworq/fireworq).
